import {useState} from 'react';
import {useActiveResource,useHandover,type DocumentRecord,type ContextResource} from '@notis/sdk';
import {Button} from '@/components/ui/button';
import {text,json,snapshotKey,type Finding} from '@/lib/analysis';
export function WorkButton({skill,prompt,label='Update analysis'}:{skill?:string;prompt?:string;label?:string}){const {handover,pending,error,available}=useHandover();const [fallback,setFallback]=useState(false);return <><Button variant="outline" size="sm" disabled={pending} onClick={()=>available?handover({skill,prompt,autoSend:false}):setFallback(!fallback)}>{label}</Button>{error&&<p role="alert">{error.message}</p>}{fallback&&<p className="research-notice">Use any assistant connected to Notis and send: {prompt||`Use ${skill}.`}</p>}</>;}
export function recordResource(row:DocumentRecord|null,kind:string):ContextResource|null{return row?{id:row.id,kind,label:row.title,revision:row.lastEditedTime||text(row,'Result digest')||text(row,'Decision digest')||'',attributes:{snapshot_key:snapshotKey(row),window_end:text(row,'Week end')||text(row,'Window end'),run_key:text(row,'Run key')},snapshot:{format:'text',content:JSON.stringify(row.properties)}}:null;}
export function ActiveRecord({row,kind}:{row:DocumentRecord|null;kind:string}){useActiveResource(recordResource(row,kind));return null;}
export function ErrorNotice({error,retry}:{error:Error|null;retry:()=>void}){return error?<div role="alert" className="research-notice">Could not refresh this data. {error.message} <button type="button" className="research-link" onClick={retry}>Retry</button></div>:null;}
export function Empty({title,children}:{title:string;children?:React.ReactNode}){return <section className="research-empty"><h2>{title}</h2><p>{children}</p></section>;}
export function Findings({rows}:{rows:Finding[]}){return <div className="analysis-findings">{rows.map((f,i)=><details className="research-disclosure" key={f.id||i} open={f.id?.startsWith('cut-')?true:undefined}><summary>{f.title}</summary><div className="research-disclosure-content">{f.body&&<p>{f.body}</p>}{f.paragraphs?.map((p,j)=><p key={j}>{p}</p>)}{f.bullets&&<ul className="list-disc pl-5 space-y-2">{f.bullets.map((p,j)=><li key={j}>{p}</li>)}</ul>}{f.tables?.map((t,j)=><div className="research-table-scroll" key={j}><table><thead><tr>{t.columns.map((c,k)=><th key={k}>{c}</th>)}</tr></thead><tbody>{t.rows.map((r,k)=><tr key={k}>{r.map((v,n)=><td key={n}>{v??'—'}</td>)}</tr>)}</tbody></table></div>)}{f.bars?.map((b,j)=><p key={j}>{b.label}: {b.value.toLocaleString('en')}{b.note?` · ${b.note}`:''}</p>)}</div></details>)}</div>;}
export function Evidence({row}:{row:DocumentRecord}){const sources=json<{label?:string;title?:string;summary?:string;detail?:string}[]>(row,'Sources',[]);return <details className="research-disclosure"><summary>Sources & method</summary><div className="research-disclosure-content"><p>{text(row,'KPI note')||'Historical evidence remains in the archived source document.'}</p><p>Method: {text(row,'KPI method')||'Unknown'}</p>{sources.map((s,i)=><p key={i}><strong>{s.label||s.title}</strong> {s.summary||s.detail}</p>)}</div></details>;}
